### ISSUE TITLE
Minor Skips when sending through forked-daapd

### ISSUE THREAD

**Issue by rccoe** [b-fitzpatrick/cpiped#1]
Thanks for this, found this in a raspberrypi forum, and successfully set it up with forked-daapd. However, the music tends to skip every 10 seconds or so, did you encounter this? And how did you fix it?

Also, I am unable to set the buffer above 0.5, only below down to about .095 works

**Comment by b-fitzpatrick** [comment]
This program exists to allow for timing mismatches between an inexpensive analog-to-digital converter (USB sound card) and the PC. Depending on which is faster, the contents of the buffer will either grow or shrink, and when the buffer runs out, the sound will skip. If it's full, it will discard samples, and if it's empty, it will insert silence. So, the larger the buffer, the longer the interval between skips, but the more severe the skip.

A 0.5s buffer was enough for my equipment to keep skips 10's of minutes apart, but I have no idea how much equipment timing varies.

I found and corrected the error that prevented a buffer larger than 0.5 seconds. I was missing a zero in the line that checks the buffer argument. I no longer use this, so I haven't tested the change. Please report back if you try it.

**Comment by rccoe** [comment]
Got it, thanks for clarifying. The extra zero fixes it and 5 seconds gives
me a much longer time between skips. Problem solved!

**Comment by b-fitzpatrick** [comment]
Great!
