### ISSUE TITLE
Slowed down playback

### ISSUE THREAD

**Issue by rccoe** [b-fitzpatrick/cpiped#2]
Hello again - I am trying to debug this but figured I could ask for your help again after your assistance last week.

Looking further into my skipping issue, it turns out it was happening every so often because the output is slightly slower playback than the input, causing overruns from time to time. The slow playback is barely noticeable, but it's there.  If I play a non-FIFO file through forked-daapd, the playback is correct so I'm thinking it must be something with the FIFO.

Any ideas on how to resolve this? I tried switching up the "val =" bitrate from 44100 to 48000, since the input through USB is coming in at 48kHz according to 

`cat /proc/asound/card0/pcm0p/sub0/hw_params

No worries if not, just kind of stuck here. Really appreciate any help you can provide.

**Comment by b-fitzpatrick** [comment]
Changing "val" to 48000 would have been my guess. It's been long enough that I don't know without spending some time trying to figure it out. Perhaps you can set your sound card to sample at 44.1 kHz.

**Comment by rccoe** [comment]
Setting up a pcm slave to sample at 44.1 worked!

For anyone else who stumbles across it:
```
vi /etc/asound.conf
pcm.device {
        format S16_LE
        rate 44100
        type hw
        card 0
        device 0
}

pcm.!default{
    type plug
    slave.pcm "device"
}
```

`cpiped -d device`
