### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by atze09** [b-fitzpatrick/cpiped#3]
Sorry for that dump question but how can i install cpiped?

i did a "git clone" and then "make", but "make install" did not work for me.
Maybe you can give me a short explanation.
Thank you in advance.

**Comment by b-fitzpatrick** [comment]
I don't think "make install" is configured. The init.d script is configured with the executable in /usr/local/bin/, so if you want to use that, just copy cpiped there and the init.d script to /etc/init.d/. You'll need to edit the init.d script with the path to the FIFO pipe, at minimum.
